
global:
  - PATH=$HOME/.local/bin:$PATH
    
services:
  - docker  

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  
jobs:
  include:
    - stage: "Build api"
      script:
      - cd $TRAVIS_BUILD_DIR
      - ./build_docker.sh api
    - stage: "Build web"
      script:
      - cd $TRAVIS_BUILD_DIR
      - ./build_docker.sh web
   