global:
  - PATH=$HOME/.local/bin:$PATH
  
    
services:
  - docker  

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli  
  - wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
  - unzip terraform_0.11.14_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_0.11.14_linux_amd64.zip 
  
jobs:
  include:
    - stage: "Build api"
      script:
      - cd $TRAVIS_BUILD_DIR
      - ./build_docker.sh api
    - stage: "Build web"
      script:
      - cd $TRAVIS_BUILD_DIR
      - ./build_docker.sh web
   